### ISSUE TITLE
suggestions / Question

### ISSUE THREAD

**Issue by Der-Flip** [kigya/NotedgeApp#3]
Hi,

I just discovered this app and so far I really love the minimal design.

First of all: In the features list and on the website (https://notedge.netlify.app/) The feature for toggling light / darkmode is being mentioned and displayed (in screenshots). I haven't found this option in the version I have installed via F-Droid.

Secondly, whenever I cancel the creation of a new note I still get the message "Note removed" which may be a bug or at least an unwanted accidental feature.

Now to some suggestions I have:
The way one deletes notes seems fairly dangerous at this point. Tap and hold to delete is okay, but it needs a confirmation. My suggestion would be changing the respective note red (instead of the default dark blue) and with another tap or tap and hold it then gets removed.

When searching for a note a way to create a note with the search term as its title. Either an extra button or just using the already existing "add note" button.

When creating a note, a way to toggle automatic bullet points for each new line

Should you be planning to extend the feature list maybe way to cross items off of a list (strikethrough by tapping element) could be fairly useful.

Finally maybe an "About" page. This one could be accessed by tapping the "Notes" headline at the top of the screen (of course only if you don't plan on implementing categories)

(okay, the actual final point now but it's really not that important: the main background colour and the note's background colour clash a bit currently. I would recommend just using a darker shade of the main background colour rather than the greenish hue that is being used now. The cyan works perfectly, though)

I know this is quite a list of items, and believe me, if I was even somehow able to coed, I would help and help implement those features, unfortunately I'm as useful as Amber Heard's poop on Johnny Depp's bed when it comes to coding and programming.
I perfectly understand and appreciate if you guys don't have the time to implement any of these, or if you think it just fits the app's theme and philosophy.

Thanks for your effort and a great notes app!

**Comment by kigya** [comment]
Hi! Thank you for such a detailed opinion. This app was conceived as my coursework project at university, so it's still not on the Play Store and remains unfinished. Your suggestions sound interesting and even quite appropriate, so thank you for that, too.
If something is added to the application from the list above, I will definitely let you know :)
